diffMappingToScore = {'Easy':0, 'Rather easy':1, 'Neutral':2, 'Rather difficult':3, 'Difficult':4}

# to check
questions = [
 {'id': 7,
  'question': ' The activity "Enter container information from documents" needs to be executed before the activity "Create new erp system entry"?',
  'type': 'multiple-choice',
  'options': "True;False;I don't know",
  'model-group': '1',
  'ExpectedAnswer': "False",
  'Type1': 'Local',
  'Type2': 'Control-flow',
  'Type3': 'Ordering'},
 {'id': 10,
  'question': ' The activity "Inform customs about temporary storage" can be executed in parallel with the activity "Inform shipping company about temporary storage"?',
  'type': 'multiple-choice',
  'options': "True;False;I don't know",
  'model-group': '1',
  'ExpectedAnswer': "False",
  'Type1': 'Local',
  'Type2': 'Control-flow',
  'Type3': 'Concurrency'},
 {'id': 13,
  'question': ' The activities "Send detailed information on final destination" and "Load container onto train" are mutually exclusive?',
  'type': 'multiple-choice',
  'options': "True;False;I don't know",
  'model-group': '1',
  'ExpectedAnswer': "True",
  'Type1': 'Local',
  'Type2': 'Control-flow',
  'Type3': 'Exclusiveness'},
 {'id': 16,
  'question': ' The activities "Request independent analysis of damage" and "Investigate cause of shake" can be executed several times?',
  'type': 'multiple-choice',
  'options': "True;False;I don't know",
  'model-group': '1',
  'ExpectedAnswer': "True",
  'Type1': 'Local',
  'Type2': 'Control-flow',
  'Type3': 'Repetition'},
 {'id': 19,
  'question': ' The activity "Drive container to scanning platform" needs to be executed before the activity "Attach accelerometer sensor"?',
  'type': 'multiple-choice',
  'options': "True;False;I don't know",
  'model-group': '1',
  'ExpectedAnswer': "False",
  'Type1': 'Global',
  'Type2': 'Control-flow',
  'Type3': 'Ordering'},
 {'id': 22,
  'question': ' The activity "Document sensor id and container id"  can be executed in parallel with the activity "Calibrate sensor"?',
  'type': 'multiple-choice',
  'options': "True;False;I don't know",
  'model-group': '1',
  'ExpectedAnswer': "False",
  'Type1': 'Global',
  'Type2': 'Control-flow',
  'Type3': 'Concurrency'},
 {'id': 25,
  'question': ' The activities "Request container deletion" and "Schedule transportation from temporary storage" are mutually exclusive?',
  'type': 'multiple-choice',
  'options': "True;False;I don't know",
  'model-group': '1',
  'ExpectedAnswer': "True",
  'Type1': 'Global',
  'Type2': 'Control-flow',
  'Type3': 'Exclusiveness'},
 {'id': 28,
  'question': ' The activities "Document results of scan in erp file" and "Log into erp system" can be executed several times?',
  'type': 'multiple-choice',
  'options': "True;False;I don't know",
  'model-group': '1',
  'ExpectedAnswer': "True",
  'Type1': 'Global',
  'Type2': 'Control-flow',
  'Type3': 'Repetition'},
 {'id': 31,
  'question': ' The activity "Reset the sensor" can only be executed after the activity "Check intensity of the shake" changes the state of the "Sensor" object to "[signalling shake]"?',
  'type': 'multiple-choice',
  'options': "True;False;I don't know",
  'model-group': '1',
  'ExpectedAnswer': "True",
  'Type1': 'Local',
  'Type2': 'Data-flow',
  'Type3': 'Data Interaction - Task to Task'},
 {'id': 34,
  'question': ' The activities "Activate accelerometer sensor" and "Load container onto forklift truck" can only be executed if the "Container" object is in the state "[offloaded]"?',
  'type': 'multiple-choice',
  'options': "True;False;I don't know",
  'model-group': '1',
  'ExpectedAnswer': "False",
  'Type1': 'Local',
  'Type2': 'Data-flow',
  'Type3': 'Task Precondition'},
 {'id': 37,
  'question': ' If the "Container" object is in state "[in transition]"  the activity "Collect container from scanning platform" is executable, whereas the activity "Collect container from temporary storage" is not executable?',
  'type': 'multiple-choice',
  'options': "True;False;I don't know",
  'model-group': '1',
  'ExpectedAnswer': "True",
  'Type1': 'Local',
  'Type2': 'Data-flow',
  'Type3': 'Data-based Routing'},
 {'id': 40,
  'question': ' The activity "Label container as scanned" can only be executed after the activtiy "Store file" changes the state of the "ERP file" object to "[saved]"?',
  'type': 'multiple-choice',
  'options': "True;False;I don't know",
  'model-group': '1',
  'ExpectedAnswer': "True",
  'Type1': 'Global',
  'Type2': 'Data-flow',
  'Type3': 'Data Interaction - Task to Task'},
 {'id': 43,
  'question': ' The activities "Request transportation from temporary storage to platform" and "Label container as shaken" can only be executed if the "Sensor" object is in the state "[idle]"?',
  'type': 'multiple-choice',
  'options': "True;False;I don't know",
  'model-group': '1',
  'ExpectedAnswer': "False",
  'Type1': 'Global',
  'Type2': 'Data-flow',
  'Type3': 'Task Precondition'},
 {'id': 46,
  'question': ' If the "Container" object is in state "[temporarily stored]"  the activity "Bring container to storage unit" is executable, whereas the activity "Schedule transportation from scanning platform" is not executable?',
  'type': 'multiple-choice',
  'options': "True;False;I don't know",
  'model-group': '1',
  'ExpectedAnswer': "True",
  'Type1': 'Global',
  'Type2': 'Data-flow',
  'Type3': 'Data-based Routing'}]

#mapping between BPMN labels and elements
labelsToElements = {'Container [offloaded]': 'DataObjectReference_1kiuc94', 'Container arrives at the dock': 'Event_0zttkou', 'Sensor [idle]': 'DataObjectReference_0hg5ejc', 'ERP file [erp open]': 'DataObjectReference_061fnhs', 'Container [lifted]': 'DataObjectReference_08dldeo', 'Attach accelerometer sensor': 'Activity_15cee8u', 'Activate accelerometer sensor': 'Activity_01cta4a', '__targetRef_placeholder': 'Property_1sn6xjp', 'Offload container from vessel': 'Activity_0f5f29o', 'Register arrival of container': 'Activity_0hiy80e', 'Label container as offloaded': 'Activity_0ytwixr', 'Load container onto forklift truck': 'Activity_010rs8r', 'Container [prepared]': 'DataObjectReference_0f4gdga', 'Document sensor id and container id': 'Activity_1gumzzz', 'Bring scanned container to temporary storage': 'Activity_0k86p0u', 'Bring scanned container to transition area': 'Activity_0q6113f', 'Container [temporarily stored]': 'DataObjectReference_12muxzn', 'Container [in transition]': 'DataObjectReference_09inboe', 'Loading time scheduled immediately?': 'Gateway_1rjxhzb', 'yes': 'Flow_0fur34x', 'no': 'Flow_07z9efj', 'Additional documentation required?': 'Gateway_1j1l81g', 'ERP file [saved]': 'DataObjectReference_03oz4yd', 'Scan the container': 'Activity_04nt2w0', 'Document results of scan in erp file': 'Activity_1diad7h', 'Drive container to scanning platform': 'Activity_0rzp71x', 'Container [scanned]': 'DataObjectReference_0tv78hq', 'Label container as scanned': 'Activity_0p4iubr', 'Onward carriage planned?': 'Gateway_109ky1m', 'Container [in storage unit]': 'DataObjectReference_02zus4a', 'Container [deleted]': 'DataObjectReference_1mxjilh', 'Bring container to storage unit': 'Activity_1u2fza9', 'Inform customs about temporary storage': 'Activity_043rk4n', 'Check location of storage unit': 'Activity_0dwvvvh', 'Request container deletion': 'Activity_00lcg2a', 'Confirm deletion of container': 'Activity_1js9ou2', 'Request transportation from temporary storage to platform': 'Activity_1fpjp2l', 'Container [transportation requested]': 'DataObjectReference_1ukbp3u', 'Inform shipping company about temporary storage': 'Activity_06wwcqs', 'Confirm transportation': 'Activity_0hsjp18', 'Container [collected]': 'DataObjectReference_18v0tz0', 'Container [loaded]': 'DataObjectReference_0se6n7x', 'Onward carriage type?': 'Gateway_1xe3mbs', 'Load container onto delivery truck': 'Activity_03y5zby', 'truck': 'Flow_1e9jzsz', 'Load container onto train': 'Activity_0v934ow', 'train': 'Flow_1c1en1o', 'Current location?': 'Gateway_1j2kukb', 'temporary storage': 'Flow_1q9gu6o', 'scanning platform': 'Flow_0r88frv', 'Collect container from temporary storage': 'Activity_0dsm76d', 'Collect container from scanning platform': 'Activity_0qpedlg', 'Schedule transportation from scanning platform': 'Activity_0qpvnoe', 'Schedule transportation from temporary storage': 'Activity_0quien2', 'Transportation request arrives': 'Event_1g3tab0', 'Send detailed information on final destination': 'Activity_1fk1rvd', 'Container file already exists?': 'Gateway_16uco3k', 'ERP file [file open]': 'DataObjectReference_0iq3wjg', 'ERP file [created]': 'DataObjectReference_0tz3nvz', 'Select shipping company in erp system': 'Activity_1xawj26', 'Create new erp system entry': 'Activity_0yjbdub', 'Select exsiting file in erp system': 'Activity_1pbl1at', 'Enter container information from documents': 'Activity_1gyhik7', 'Store file': 'Activity_1nmp9fg', 'Log into erp system': 'Activity_1cmvqgw', 'Analysis successful?': 'Gateway_0v4m75q', 'Check intensity of the shake': 'Activity_0jrye11', 'Calibrate sensor': 'Activity_0p2t8c9', 'Shake event': 'Event_0d6p2ki', 'Sensor [signalling shake]': 'DataObjectReference_0vbkjhn', 'Reset the sensor': 'Activity_0zu0ga9', 'Label container as shaken': 'Activity_1cfg5ub', 'Open the container to evaluate damage': 'Activity_17yxenk', 'Low intensity?': 'Gateway_0kv0pm1', 'Request independent analysis of damage': 'Activity_186kdlf', 'Investigate cause of shake': 'Activity_08p36ck', 'scanned': 'Event_0jmaqvy', 'temporarily stored': 'Event_1mmc4ra', 'offloaded': 'Event_1skb0fk', 'collected': 'Event_0vyiqzr', 'loaded': 'Event_18j0fkn', 'deleted': 'Event_1jdt498', 'lifted': 'Event_055ekxh', 'in transition': 'Event_1we1c83', 'transportation requested': 'Event_113zl9w', 'in storage unit': 'Event_0v1ae5r', 'prepared': 'Event_10n5irp', 'file open': 'Event_0w9feqf', 'saved': 'Event_08uzq0x', 'erp open': 'Event_0s4uxqm', 'created': 'Event_0sj5i77', 'idle': 'Event_074rzm6', 'signalling shake': 'Event_1a9z78r'}